services:
#    atelier_andrea.example:
#        class: Atelier\AndreaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    form.service:
        class: Atelier\AndreaBundle\Services\FormService

    rendez_vous.metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments: [Atelier\AndreaBundle\Entity\RendezVous]

    rendez_vous.repository:
        class: Atelier\AndreaBundle\Repository\RendezVousRepository
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@rendez_vous.metadata'

    rendez_vous.service:
        class: Atelier\AndreaBundle\Services\RdvService
        arguments: ['@rendez_vous.repository']

