<?php

namespace Atelier\AndreaBundle\Repository;

/**
 * CollaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaborateurRepository extends \Doctrine\ORM\EntityRepository
{
}
